### ISSUE TITLE
בדיקת מטלה 3

### ISSUE THREAD

**Issue by michael-lemberger** [gamedev-srg/First-Unity#1]
למרות שהמשחק מעולה כי הוא בתלת מימד, יש מלא מספרי קסם בקוד. איך מתכנת שלא לקח חלק בפיתוח של המשחק ידע מה מספרים אלה אומרים?

**Comment by ShmuelLa** [comment]
קיבלנו, לא קרה ולא יקרה יותר :) 
תודה!
